var students = {
    "Aditya Jaiswal":"Aditya@123",
    "Mohd Faizan":"Faizan@123",
    "Divyanshu Jaiswal":"Divyanshu@123",
    "Mohammad Ali":"Mohammad@123",
    "Shubham Dubey":"Shubham@123",
    "Ritesh Gupta":"Ritesh@123",
    "Krishna Yadav":"Krishna@123",
    "Manoj Kumar Yadav":"Manoj@123",
    "Shivansh Dubey":"Shivansh@123",
    "Chandan Yadav":"Chandan@123",
    "Ajay Kumar Gupta":"Ajay@123",
    "Mohd Hamid Siddique":"Hamid@123",
    "Aman Kumar Pal":"Aman@123",
    "Chandra Prakash":"Chandra@123",
    "Shobha Ram":"Shobha@123",
    "Sambhu Chauhan":"Sambhu@123",
    "Saurabh Verma":"Saurabh@123",
    "Abhay Singh":"Abhay@123",
    "Manish Yadav":"Manish@123",
    "Ram Autar Verma":"Ram@123",
    "Amarnath":"Amar@123",
    "Kaushal Mishra":"Kaushal@123",
    "Suneel Kumar":"Suneel@123",
    "Ankit Chauhan":"Ankit@123",
    "Shobhit Verma":"Shobhit@123",
    "Anoop Maurya":"Anoop@123",
    "Rajesh Verma":"Rajesh@123",
    "Saurabh Maurya":"Saurabh@123",
    "Ankit Prajapati":"Ankit@123",
    "Tanmay Jaiswal":"Tanmay@123",
    "Saurabh Chaurasiya":"Saurabh@123",
    "Vivek Paswan":"Vivek@123",
    
    "Mahek Srivastava":"Mahek@123",
    "Vijay Laxmi Shukla":"Laxmi@123",
    
    "Beauty Shukla":"Beauty@123",
    "Anshika Maurya":"Anshika@123",
    "Anshika Kushwaha":"Anshika@123",
    "Vandana":"Vandana@123",
    "Vanshika Mathur":"Vanshika@123",
    "Swati Sharma":"Swati@123",
    "Kajal Goswami":"Kajal@123",
    "Vibha":"Vibha@123",
    "Pooja Yadav":"Pooja@123",
    "Usha Maurya":"Usha@123",
    "Kumkum":"Kumkum@123",
    "Shalini Maurya":"Shalini@123",
    "Jyoti Giri":"Jyoti@123",
    "Pooja Maurya":"Pooja@123",
    "Shivani Singh":"Shivani@123",
    "Ankita Kanojiya":"Ankita@123",
    "Shiv Nandini":"Shiv@123",
    "Seema Maurya":"Seema@123",
    "Nidhi Pal":"Nidhi@123",
    "Kumkum Kashyap":"Kumkum@123",
    
    "Ankur":"Ankur@oipl",
    "Ankit Kumar":"Ankit@oipl",
    "Lakhan Lal":"Lakhan@oipl",
    "Shiv Baksh":"Shiv@oipl",
    "Ankit Kumar Verma":"Ankit@oipl",
    "Tushar Singh":"Tushar@oipl",
    "Vikas Pandey":"Vikas@oipl",
    "Shrit Kashyap":"Shrit@oipl",
    "Piyush Giri":"Piyush@oipl",
    "Awaneesh Maurya":"Awaneesh@oipl",
    "Kuldeep Yadav":"Kuldeep@oipl",
    "Budh Ram Yadav":"Budh@oipl",
    "Anshul Mishra":"Anshul@oipl",
    "Rajneesh Tiwari":"Rajneesh@oipl",
    "Noor Alam":"Noor@oipl",
    "Gangesh Sharma":"Gangesh@oipl",
    "Rupendra Tiwari":"Rupendra@oipl",
    "Kafil Ahmad":"Kafil@oipl",
    "Maneesh Kumar Chauhan":"Maneesh@oipl",
    "Ayush Kumar Mishra":"Ayush@oipl",
    "Virendra Singh":"Virendra@oipl",
    "Satyam Srivastava":"Satyam@oipl",
    "Ranjeet Sonkar":"Ranjeet@oipl",
    "Archana Yadav":"Archana@oipl",
    "Madhu Mishra":"Madhu@oipl",
    "Laki Pandey":"Laki@oipl",
    "Afreen":"Afreen@oipl",
    "Neelu Devi Maurya":"Neelu@oipl",
    "Shanta":"Shanta@oipl",
    "Seema Patel":"Seema@oipl",
    "Nandini Maurya":"Nandini@oipl",
    "Laxmi Tiwari":"Laxmi@oipl",
    "Dipali Gupta":"Dipali@oipl",
    "Manisha Devi":"Manisha@oipl",
    "Komal":"Komal@oipl",
    "Renu Devi":"Renu@oipl",
    "Sankalp Vishwakarma":"Sankalp@oipl",
    "Ashutosh Tiwari":"Ashutosh@oipl",
    "Shubham Rajbhar":"Shubham@oipl",
    "Neha Tiwari":"Neha@oipl",
    "Khushboo Yadav":"Khushboo@oipl",
    "Vishal Jaiswal":"Vishal@oipl",
    "Vibhansh Yadav":"Vibhansh@oipl",
    "Ashwani Tiwari":"Ashwani@oipl",
    "Purnima Maurya":"Purnima@oipl",
    "Anjali Kashyap":"Anjali@oipl",
    "Aditya":"Aditya@oipl",
    "Brijesh Tiwari":"Brijesh@oipl",
    "Fardeen Sidiqqui":"Fardeen@oipl",
    "Ankit Tiwari":"Ankit@oipl",
    "Aadarsh Goswami":"Aadarsh@oipl",
    "Saurabh Singh":"Saurabh@oipl",
    "Vivek Rao":"Vivek@oipl",
    "Arti Devi Gupta":"Arti@oipl",
    "Vaishnavi":"Vaishnavi@oipl",
    "Nidhi Singh":"Nidhi@oipl",
    "Akanksha Singh":"Akanksha@oipl",
    
    




    

    "Urmila Devi":"Urmila@123",
    "Suneel Verma":"Suneel@123",
    "Sadhna Yadav":"Sadhna@123",
    "Aradhna Yadav":"Aradhna@123",
    "Pinki Verma":"Pinki@123",
    "Shivam Jaiswal":"Shivam@123",
    "Arpit Jaiswal":"Arpit@123",
    "Siyaram":"Siyaram@123",
    "Mohd Juned":"Juned@123",
    "Ashok Kumar":"Ashok@123",
    "Shivam Chaurasiya":"Shivam@123",
    "Sachin Kumar":"Sachin@123",
    "Karan Prajapati":"Karan@123",
    "Amit Sharma":"Amit@123",
    "Kalp Nath Yadav":"Kalp@123",
    "Raman Kumar":"Raman@123",
    "Suraj Gupta":"Suraj@123",
    "Shailendra Kumar":"Shailendra@123",
    "Rekha Yadav":"Rekha@123",
    "Anshu Yadav":"Anshu@123",
    "Hazra Bano":"Hazra@123",
    "Radhika Namdev":"Radhika@123",
    "Arti Yadav":"Arti@123",
    "Shivani Kashyap":"Shivani@123",
    "Khusi Kashyap":"Khusi@123",
    "Jooli":"Jooli@123",
    "Sushmita Verma":"Sushmita@123",
    "Nandini Sharma":"Nandini@123",
    "Harsh Kumar Sahu":"Harsh@123",
    "Manish Chaurasiya":"Manish@123",
    "Sonu Nishad":"Sonu@123",
    "Awadesh Chaurasiya":"Awadesh@123",
    "Mahesh":"Mahesh@123",
    "Kumkum":"Kumkum@123",
    "Vikas Maurya":"Vikas@123",
    "Laxmi":"Laxmi@123",
    "Rishabh Dubey":"Rishabh@123",
    "Ranjeet Kumar":"Ranjeet@123",
    "Dileep Yadav":"Dileep@123",
    "Anand Prakash":"Anand@123",
    "Savitri Maurya":"Savitri@123",
    "Khusi Singh":"Khusi@123",
    "Manisha Verma":"Manisha@123",
    "Shyam Sharan Patel":"Shyam@123",
    "Harshit Shukla":"Harshit@123",
    "Phoolchand":"Phoolchand@123",
    "Vikas Chaurasiya":"Vikas@123",
    "Nidhi Mishra":"Nidhi@123",
    "Shivani Tiwari":"Shivani@123",
    "Akhilesh Prajapati":"Akhilesh@123",
    "Vishal":"Vishal@123",
    "Anand Sidharth":"Anand@123",
    "Madhu Patel":"Madhu@123",
    "Deepak Singh":"Deepak@123",
    "Sandhya Shukla":"Sandhya@123",
    "Priyanshi Yadav":"Priyanshi@123",
    "Manoj Kumar":"Manoj@123",
    "Ranjeet Maurya":"Ranjeet@123",
    "Hariom Goswami":"Hariom@123",
    "Shriom Maurya":"Shriom@123",
    "Ravi Kumar":"Ravi@123",
    "Sadanand Yadav":"Sadanand@123",
    "Akhilesh Yadav":"Akhilesh@123",
    "Alok Kumar":"Alok@123",
    "Amit Verma":"Amit@123",
    "Samar Verma":"Samar@123",
    "Mayank Jaiswal":"Mayank@123",
    "Ashish Verma":"Ashish@123",
    "Ankit Tiwari":"Ankit@123",
    "Vikram Kashyap":"Vikram@123",
    "Vandana Mishra":"Vandana@123",
    "Swati Pandey":"Swati Pandey@123",
    "Laxmi Kashyap":"Laxmi@123",
    "Vikas Maurya":"Vikas@123",
    "Kavya Pandey":"Kavya@123",
    "Alok Pandey":"Alok@123",
    "Dipesh Yadav":"Dipesh@123",
    "Srishti Pandey":"Srishti@123",
    "Devanjali Singh":"Devanjali@123",
    "Nidhi Awasthi":"Nidhi@123",
    "Roli Vajpayi":"Roli@123",
    "Priyanka Verma":"Priyanka@123",
    "Suman Bharti":"Suman@123",
    "Suraj Shukla":"Suraj@123",
    "Amit Shukla":"Amit@123",
    "Ram Shukla":"Ram@123",
    "Surabh Dubey":"Saurabh@123",
    "Nitin Kumar":"Nitin@123",
    "Akash Tiwari":"Akash@123",
    "Sushant Sharma":"Sushant@123"
    
    
    

}
