var students = {
    "Iqra Alvi":"Iqra@oipl",
    "Ayushi Verma":"Ayushi@oipl",
    "Kajal Maurya":"Kajal@oipl",
    "Arti Jaiswal":"Arti@oipl",
    "Shraddha Mishra":"Shraddha@oipl",
    "Archana Jaiswal":"Archana@oipl",
    "Kishan Jaiswal":"Kishan@oipl",
    "Ajay Verma":"Ajay@oipl",
    "Umesh Kumar":"Umesh@oipl",
    "Rajesh Verma":"Rajesh@oipl",
    "Himanshu Singh":"Himanshu@oipl",
    "Sandeep Kumar Sonkar":"Sandeep@oipl",
    "Anurag":"Anurag@oipl",
    "Saroj Chauhan":"Saroj@oipl",
    "Anjana Maurya":"Anjana@oipl",
    
    "Mahesh Kumar":"Mahesh@123",
    "Alok Pandey":"Alok@123",
    "Prem Vishwakarma":"Prem@123",
    "Akhilesh Yadav":"Akhilesh@123",
    "Rohit Maurya":"Rohit@123",
    "Shivnandan Sharma":"Shivnandan@123",
    "Nauhar":"Nauhar@123",
    "Dinesh Verma":"Dinesh@123",
    "Amarjeet":"Amarjeet@123",
    "Akash Kumar":"Akash@123",
    "Gulzar Shah":"Gulzar@123",
    "Nanbabu":"Nanbabu@123",
    "Anand Kishor Goswami":"Anand@123",

    "Ramsagar Shahu":"Ram@oipl",
    
    
    "Sakshi Mishra":"Sakshi@oipl",
    
    
    "Laxmi Verma":"Laxmi@oipl",
    
    
   
    "Shyambabu Pandey":"Shyam@oipl",
    "Shiva":"Shiva@oipl",
    "Vaibhav Singh":"Vaibhav@oipl",
    "Prince Singh":"Prince@oipl",
    
    
    "Mahi Sagar":"Mahi@123",
    
    "Himali Pandey":"Himali@123",
    "Aradhya Patwa":"Aradhya@123",
    "Astha Kumari":"Astha@123",
    "Umesh Tiwari":"Umesh@123",
    "Vishal Shukla":"Vishal@123",
    "Anuj Shukla":"Anuj@123",
    "Anmol Ratan Tiwari":"Anmol@123",
    "Priyanshu Shukla":"Priyanshu@123",
    "Vishal Mishra":"Vishal@123",
    
    "Prachi Tiwari":"Prachi@123",

    "Pramila Yadav":"Pramila@oipl",
    "Rekha Kashyap":"Rekha@oipl",
    "Ankita Kanojiya":"Ankita@oipl",
    "Aditi Singh":"Aditi@oipl",
    "Simran Yadav":"Simran@oipl",
    "Akanksha Chaurasia":"Akanksha@oipl",
    "Anjali Singh":"Anjali@oipl",
    "Shalini Shukla":"Shalini@oipl",
    "Yishu Modanwal":"Yishu@oipl",
    "Sakshi Mishra":"Sakshi@oipl",
    "Talmun Nishad":"Talmun@oipl",
    "Taniya Kashyap":"Taniya@oipl",
    "Manish Kumar":"Manish@oipl",
    "Mohd Akib":"Mohd@oipl",
    "Krishna Mishra":"Krishna@oipl",
    "Pankaj Kashyap":"Pankaj@oipl",
    "Ashish Kuldeep":"Ashish@oipl",
    "Shivam Kashyap":"Shivam@oipl",
    "Harsh Pandey":"Harsh@oipl",
    "Rajendra Singh":"Rajendra@oipl",
    "Prashant Mishra":"Prashant@oipl",
    "Trisha Mishra":"Trisha@oipl",
    "Kavita Pal":"Kavita@oipl",
    
    "Komal Pandey":"Komal@oipl",
    "Anjali Shukla":"Anjali@oipl",
    "Sanika Tripathi":"Sanika@oipl",
    "Anurag Rao":"Anurag@oipl",
    "Puttan Kumar":"Puttan@oipl",
    "Saurabh Dwivedi":"Saurabh@oipl",
    "Ritesh Shukla":"Ritesh@oipl",
    "Shyam Babu":"Shyam@oipl",
    "Anjali Kashyap":"Anjali@123",
    "Divyanshi Tiwari":"Divyanshi@oipl",
    "Disha Tiwari":"Disha@oipl",
    "Azka Khan":"Azka@oipl",
    "Anju Kashyap":"Anju@123",
    "Laxmi Devi":"Laxmi@123",
    "Saloni":"Saloni@oipl",
    "Shivam Shukla":"Shivam@oipl",
    "Abhishek Shukla":"Abhishek@oipl",
    "Mukul Dwivedi":"Mukul@oipl",
    "Nikhil Singh":"Nikhil@oipl",
    "Ayush Mishra":"Ayush@oipl",
    "Vaibhav Modanwal":"Vaibhav@oipl",
    "Satyam Chaudhary":"Satyam@oipl",
    "Upasna Devi":"Upasna@oipl",
    
    "Suneel Verma":"Suneel@123",
    "Sadhna Yadav":"Sadhna@123",
    "Aradhna Yadav":"Aradhna@123",

    "Rajan":"Rajan@oipl",
    "Kaif":"Kaif@oipl",
    "Satyam":"Satyam@oipl",
    "Pradeep":"Pradeep@oipl",
    "Ankit":"Ankit@oipl",
    "Vishnu":"Vishnu@oipl",
    "Vijay":"Vijay@oipl",
    "Harish":"Harish@oipl",
    "Ahad":"Ahad@oipl",
    "Rakesh":"Rakesh@oipl",
    "Waris":"Waris@oipl",
    "Ruchi":"Ruchi@oipl",
    "Rajni":"Rajni@oipl",
    "Mariyam":"Mariyam@oipl",
    "Nivedita":"Nivedita@oipl",
    "Neha":"Neha@oipl",
    "Garima":"Garima@oipl",
    "Kajal":"Kajal@oipl",
    "Komal":"Komal@oipl",
    "Khushbu Gupta":"Khushbu@oipl",
    "Ishita":"Ishita@oipl",
    "Mala":"Mala@oipl",
    "Khushbu Verma":"Khushbu@oipl",
    "Siya":"Siya@oipl",
    "Mahek":"Mahek@oipl",
    "Muskan":"Muskan@oipl",
    "Alok":"Alok@oipl",
    "Loknath":"Loknath@oipl",
    "Sarvan":"Sarvan@oipl",
    "Divyanshi":"Divyanshi@oipl",
    "Jitendra":"Jitendra@oipl",

    "Abhishek Kumar":"Abhishek@oipl",
    "Abhishek Verma":"Abhishek@oipl",
    "Aadarsh Pathak":"Aadarsh@oipl",
    "Akash Pal":"Akash@oipl",
    "Akashdeep Verma":"Akashdeep@oipl",
    "Aman Chaudhary":"Aman@oipl",
    "Anand Pathak":"Anand@oipl",
    "Anurag Singh":"Anurag@oipl",
    "Arpit Sharma":"Arpit@oipl",
    "Ashish Pathak":"Ashish@oipl",
    "Ashish Tiwari":"Ashish@oipl",
    "Chandrakesh Verma":"Chandrakesh@oipl",
    "Deepak Paswan":"Deepak@oipl",
    "Harish Shukla":"Harish@oipl",
    "Jainendra":"Jainendra@oipl",
    "Mohd Moshim":"Mohd@oipl",
    "Mohini Maurya":"Mohini@oipl",
    "Neeta Yadav":"Neeta@oipl",
    "Niraj Yadav":"Niraj@oipl",
    "Pranjal Sharma":"Pranjal@oipl",
    "Rahul Pandey":"Rahul@oipl",
    "Raj Singh":"Raj@oipl",
    "Ram Karan Yadav":"Ram@oipl",
    "Reeta Vishwakarma":"Reeta@oipl",
    "Rohit Kumar Maurya":"Rohit@oipl",
    "Saniya Bano":"Saniya@oipl",
    "Shiva Verma":"Shiva@oipl",
    "Shivam Rawat":"Shivam@oipl",
    "Surendra Giri":"Surendra@oipl",
    "Vibha Maurya":"Vibha@oipl",
    "Vishwajeet Pal":"Vishwajeet@oipl",
    "Yogesh Mishra":"Yogesh@oipl",


    "Akansha Yadav":"oipl@123",
    "Alshifa":"oipl@123",
    "Amit Vishwakarma":"oipl@123",
    "Aneel Kumar":"oipl@123",
    "Anoop Nishad":"oipl@123",
    "Anshika Jaiswal":"oipl@123",
    "Ayushi Verma":"oipl@123",
    "Deepak Kumar":"oipl@123",
    "Deepak Verma":"oipl@123",
    "Deepti Verma":"oipl@123",
    "Janvi":"oipl@123",
    "Jatin Kashyap":"oipl@123",
    "Jyoti Gupta":"oipl@123",
    "Laxmi Devi":"oipl@123",
    "Mahima Chauhan":"oipl@123",
    "Manish Kumar Yadav":"oipl@123",
    "Manisha Verma":"oipl@123",
    "Pinki Verma":"oipl@123",
    "Pinki Yadav":"oipl@123",
    "Prachi Chauhan":"oipl@123",
    "Preeti Yadav":"oipl@123",
    "Rahul Verma":"oipl@123",
    "Rajesh Verma":"oipl@123",
    "Ravi Yadav":"oipl@123",
    "Ritesh Verma":"oipl@123",
    "Rubi Vishwakarma":"oipl@123",
    "Ruchi Vishwakarma":"oipl@123",
    "Sadab":"oipl@123",
    "Sandeep Kumar":"oipl@123",
    "Shahnoor":"oipl@123",
    "Shani Nishad":"oipl@123",
    "Shika Sharma":"oipl@123",
    "Shiva":"oipl@123",
    "Uday Jaiswal":"oipl@123",
    "Umesh Verma":"oipl@123",
    "Vishal Gupta":"oipl@123",
    "Zoya Bano":"oipl@123",
    "Ritesh":"oipl@123",

    "Nandini Dwivedi":"Nandini@oipl",
    "Sangini Singh":"Sangini@oipl",
    "Khushi Devi":"Khushi@oipl",
    "Kajal Tiwari":"Kajal@oipl",
    "Janhvi Singh":"Janhvi@oipl",
    "Shivani Gupta":"Shivani@oipl",
    "Mridushi Tiwari":"Mridushi@oipl",
    "Soumya Srivastava":"Soumya@oipl",
    "Anushka Singh":"Anushka@oipl",
    "Tannu Soni":"Tannu@oipl",
    "Divyanshi Singh":"Divyanshi@oipl",
    "Tarik Khan":"Tarik@oipl",
    "Rahul Kumar Dwivedi":"Rahul@oipl",
    "Abhishek Mishra":"Abhishek@oipl",
    "Nitesh Srivastava":"Nitesh@oipl",

    "Sharad Tiwari":"Sharad@oipl",
    "Faizal":"Faizal@oipl",
    "Krishna Pandey":"Krishna@oipl",
    "Diwakar Chaturvedi":"Diwakar@oipl",
    "Harshita Vaishya":"Harshita@oipl",
    "Saumya Shukla":"Saumya@oipl",
    "Babli Tiwari":"Babli@oipl",
    "Mohd Azeem":"Azeem@oipl",
    "Saumya Singh":"Saumya@oipl",
    "Vivek Shukla":"Vivek@oipl",
    "Durgesh Singh":"Durgesh@oipl",
    "Ashirwad Dixit":"Ashirwad@oipl",
    "Sachin Awasthi":"Sachin@oipl",
    "Ragini Kashyap":"Ragini@oipl",
    "Priya Gupta":"Priya@oipl",
    "Amit Rao":"Amit@oipl",
    "Hariom Tiwari":"Hariom@oipl",


    
    "Vikash Tiwari":"Vikash@oipl",
    "Nauman Khan":"Nauman@oipl",
    "Rishi Mishra":"Rishi@oipl",
    "Anoop Tiwari":"Anoop@oipl",
    "Prince Tiwari":"Prince@oipl",
    
    
}



