var students = {
    "Shubham Sharma":"Shubham",
    "Ranjeet Mishra":"Ranjeet",
    "Pinki Mishra":"Pinki",
    "Julli Arya":"Julli",
    "Tanu Shukla":"Tanu",
    "Raunak Srivastava":"Raunak",
    
    "Shivam Mishra":"Shivam",
    "Mudrika Srivastava":"Mudrika",
    "Raj Narayan":"Raj",
    "Kajal Shukla":"Kajal",

    "Akash Singh":"Akash",
    "Akansha Tiwari":"Akansha",
    "Garima Singh":"Garima",

    "Vinay Mishra":"Vinay",
    "Priyanshu Mishra":"Priyanshu",
    "Tushar Srivastava":"Tushar",
    "Abhishek Sharma":"Abhishek",
    "Abdul Ansari":"Abdul",
    "Kalpana Srivastava":"Kalpana",
    "Brijesh Mishra":"Brijesh",
    "Shubham Mishra":"Shubham",
    "Aradhya Srivastava":"Aradhya",
    "Subhi Singh":"Subhi",
    "Vivek Khasyap":"Vivek",
    "Mamta Verma":"Mamta",
    "Karan Paswan":"Karan",

    "Sweta Gaur":"Sweta",
    "Shubham Vishwakarma":"Shubham",
    "Sunil Chaudhary":"Sunil",
    "Nirupma Pandey":"Nirupma",
    "Jyotsana":"Jyotsana",

    "Shivani Maurya":"Shivani",
    "Sandhya Tiwari":"Sandhya",
    "Pragya":"Pragya",
    "Neelu":"Neelu",
    "Mohd Irshad":"Irshad",
    "Mukesh Mishra":"Mukesh",
    "Prema Devi":"Prema",
    
    "Dinesh Mishra":"Dinesh",
    "Suman Mishra":"Suman",
    
    "Manisha":"Manisha",
    "Suman Sharma":"Suman",
    "Isha Jaiswal":"Isha",
    "Mohit Tiwari":"Mohit",
    "Shivansh Tiwari":"Shivansh",
    "Saurabh Pandey":"Saurabh",
    "Ankit Chaudhary":"Ankit",
    "Pradeep Yadav":"Pradeep",
    "Samiksha Tiwari":"Samiksha",
    "Sachin":"Sachin",
    "Soniya":"Soniya",
    "Subhi Mishra":"Subhi",
    "Raghuvanshmani":"Raghuvanshmani",
    "Anurag Singh":"Anurag"
};
