var students = {
    "Shubham Sharma":"Shubham",
    "Vimal Chaubey":"Vimal",
    "Manish Jaiswal":"Manish",
    "Ranjeet Mishra":"Ranjeet",
    "Pinki Mishra":"Pinki",
    "Julli Arya":"Julli",
    "Tanu Shukla":"Tanu",
    "Pramila":"Pramila",
    "Raunak Srivastava":"Raunak",
    "Akash Singh":"Akash",
    "Akansha Tiwari":"Akansha",
    "Garima Singh":"Garima",
    "Vinay Mishra":"Vinay",
    "Priyanshu Mishra":"Priyanshu",
    "Tushar Srivastava":"Tushar",
    "Abhishek Sharma":"Abhishek",
    "Abdul Ansari":"Abdul",
    "Kalpana Srivastava":"Kalpana",
    "Brijesh Mishra":"Brijesh",
    "Shubham Mishra":"Shubham",
    "Aradhya Srivastava":"Aradhya",
    "Subhi Singh":"Subhi",
    "Vivek Khasyap":"Vivek",
    "Mamta Verma":"Mamta",
    "Sweta Gaur":"Sweta",
    "Prince Chaurasiya":"Prince",
    "Silpi Chaurasiya":"Shilpi",
    "Anshika Chaurasiya":"Anshika",
    "Komal Mishra":"Komal",
    "Hemant":"Hemant",
    "Pratibha Ranjan":"Pratibha",
    "Vedant Upadhyay":"Vedant",
    "Shubham Vishwakarma":"Shubham",
    "Sushant Upadhyay":"Sushant",
    "Sunil Chaudhary":"Sunil"
};
