var students = {
    "Shubham Sharma":"Shubham",
    "Vimal Chaubey":"Vimal",
    "Manish Jaiswal":"Manish",
    "Ranjeet Mishra":"Ranjeet",
    "Pinki Mishra":"Pinki",
    "Julli Arya":"Julli",
    "Tanu Shukla":"Tanu",
    "Pramila":"Pramila",
    "Raunak Srivastava":"Raunak",
    "Akash Singh":"Akash",
    "Akansha Tiwari":"Akansha",
    "Garima Singh":"Garima",
    "Vinay Mishra":"Vinay",
    "Priyanshu Mishra":"Priyanshu",
    "Abhishek Sharma":"Abhishek",
    "Abdul Rahman":"Abdul",
    "Kalpana Srivastava":"Kalpana",
    "Brijesh Mishra":"Brijesh",
    "Shubham Mishra":"Shubham",
    "Aradhya":"Dev",
    "Subhi Singh":"Subhi",
    "Vivek Khasyap":"Vivek",
    "Mamta Verma":"Mamta",
    "Tushar Srivastava":"Tushar",
};
