var students = {
    "Shubham Sharma":"Shubham",
    "Vimal Chaubey":"Vimal",
    "Manish Jaiswal":"Manish",
    "Ranjeet Mishra":"Ranjeet",
    "Pinki Mishra":"Pinki",
    "Julli Arya":"Julli",
    "Tanu Shukla":"Tanu",
    "Pramila":"Pramila",
    "Raunak Srivastava":"Raunak",
    "Akash Singh":"Akash",
    "Akansha Tiwari":"Akansha",
    "Garima Singh":"Garima",
    "Vinay Mishra":"Vinay",
    "Priyanshu Mishra":"Priyanshu",
    "Tushar Srivastava":"Tushar",
    "Abhishek Sharma":"Abhishek",
    "Abdul Ansari":"Abdul",
    "Kalpana Srivastava":"Kalpana",
    "Brijesh Mishra":"Brijesh",
    "Shubham Mishra":"Shubham",
    "Aradhya Srivastava":"Aradhya",
    "Subhi Singh":"Subhi",
    "Vivek Khasyap":"Vivek",
    "Mamta Verma":"Mamta",
    "Shusant Upadhyay":"SU123",
    "Vedant Upadhyay":"VU11",
    "Shubham Vishwakarma":"Shubham",
    "Sweta Gaur":"SG156",
    "Shilpi Chaurasiya":"SC555",
    "Anshika Chaurasiya":"AC222",
    "Prince Chaurasiya":"PC333",
    "Komal Mishra":"KM666",
    "Pratibha Ranjan":"PR156",

};
